# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy everything and run prod build
COPY . .
RUN chmod +x ./prod-build.sh && ./prod-build.sh

# Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Expose port and start app
EXPOSE 80
ENTRYPOINT ["dotnet", "GameStore.Api.dll"]
