### root route
GET  http://localhost:5094

### get games details
GET http://localhost:5094/games

### get specific game details
GET http://localhost:5094/games/1

### post new games
POST http://localhost:5094/games
Content-Type: application/json

{
    "name": "Stardew Valley",
    "genreId": 2,
    "price": 5.99,
    "releaseDate": "2016-02-26"
}

### update a game
PUT http://localhost:5094/games/5
Content-Type: application/json

{
    "name": "Tekken 8",
    "genre": "Fighting",
    "price": 28.55,
    "releaseDate": "2024-02-13"
}

### delete a game
DELETE  http://localhost:5094/games/2