### root route
GET  http://localhost:5094

### get games details
GET http://localhost:5094/games

### get specific game details
GET http://localhost:5094/games/5

### post new games
POST http://localhost:5094/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

### update a game
PUT http://localhost:5094/games/5
Content-Type: application/json

{
    "name": "Tekken 8",
    "genreId": 1,
    "price": 28.55,
    "releaseDate": "2024-02-13"
}

### delete a game
DELETE  http://localhost:5094/games/7