###
GET http://localhost:5094/games

###
POST http://localhost:5094/games
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

God of War
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="genreId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

59.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="releaseDate"

2022-01-01
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

A mythological action game
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="publisher"

Santa Monica Studio
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="gow.jpg"
Content-Type: image/jpeg

< ./gow.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
PUT http://localhost:5094/games/4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXyz123

------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="name"

Updated Game
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="genreId"

2
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="price"

49.99
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="releaseDate"

2023-01-01
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="description"

Updated description
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="publisher"

Updated Publisher
------WebKitFormBoundaryXyz123
Content-Disposition: form-data; name="image"; filename="updated.jpg"
Content-Type: image/jpeg

< ./updated.jpg
------WebKitFormBoundaryXyz123--


###
DELETE http://localhost:5094/games/3
